import React, { useState, useEffect } from 'react';
import { 
  UserPlus, 
  Calendar, 
  BookOpen, 
  MapPin, 
  Clock, 
  User, 
  CheckCircle, 
  X,
  Plus,
  RefreshCw,
  FileSpreadsheet,
  FilePlus2,
  Trash2,
  Undo2,
  AlertCircle,
  RotateCcw
} from 'lucide-react';
import { SpreadsheetData, DataRecord } from '../types';

interface DedicatedFormProps {
  data: SpreadsheetData;
  onAddRow: (newRow: DataRecord) => void;
  onDeleteRow: (index: number) => void;
  onRenameOption: (colName: string, oldValue: string, newValue: string) => void;
}

export default function DedicatedForm({ data, onAddRow, onDeleteRow, onRenameOption }: DedicatedFormProps) {
  const { columns, rows } = data;

  // Form State
  const [formData, setFormData] = useState<{ [key: string]: string }>({});
  const [errors, setErrors] = useState<{ [key: string]: string }>({});
  
  // Custom unique value adder state (to add a value not in the distinct values array)
  const [customValues, setCustomValues] = useState<{ [key: string]: string }>({});
  const [showCustomInput, setShowCustomInput] = useState<{ [key: string]: boolean }>({});

  // States for rename / edit options panel
  const [showEditOptions, setShowEditOptions] = useState<{ [key: string]: boolean }>({});
  const [editingOptionIndex, setEditingOptionIndex] = useState<{ [key: string]: number | null }>({});
  const [editingOptionText, setEditingOptionText] = useState<{ [key: string]: string }>({});

  const toggleEditOptions = (colName: string) => {
    setShowEditOptions(prev => ({ ...prev, [colName]: !prev[colName] }));
    setEditingOptionIndex(prev => ({ ...prev, [colName]: null }));
    setEditingOptionText(prev => ({ ...prev, [colName]: '' }));
  };

  const startEditingOption = (colName: string, index: number, currentValue: string) => {
    setEditingOptionIndex(prev => ({ ...prev, [colName]: index }));
    setEditingOptionText(prev => ({ ...prev, [colName]: currentValue }));
  };

  const saveEditedOption = (colName: string, index: number, oldValue: string) => {
    const newValue = String(editingOptionText[colName] || '').trim();
    if (!newValue) {
      alert("O novo valor não pode ser vazio.");
      return;
    }
    if (newValue === oldValue) {
      setEditingOptionIndex(prev => ({ ...prev, [colName]: null }));
      return;
    }
    
    // Call the parent to rename across state
    if (onRenameOption) {
      onRenameOption(colName, oldValue, newValue);
    }
    
    // If the currently selected form value was the old value, update it in local form state as well
    if (formData[colName] === oldValue) {
      setFormData(prev => ({ ...prev, [colName]: newValue }));
    }
    
    // Reset editing index
    setEditingOptionIndex(prev => ({ ...prev, [colName]: null }));
  };
  
  // Local session additions tracker
  const [sessionAdditions, setSessionAdditions] = useState<{ row: DataRecord; originalIndex: number }[]>([]);
  const [formSuccess, setFormSuccess] = useState<string | null>(null);

  // Key primary auto-generation toggle
  const [autoGenKey, setAutoGenKey] = useState(true);

  // Read columns and setup initial default states
  useEffect(() => {
    resetForm();
  }, [columns]);

  const resetForm = () => {
    const initialForm: { [key: string]: string } = {};
    const initialCustoms: { [key: string]: string } = {};
    const initialCustomToggles: { [key: string]: boolean } = {};

    columns.forEach(col => {
      if (col.type === 'date') {
        // Pre-fill today's date
        initialForm[col.name] = new Date().toISOString().split('T')[0];
      } else if (col.type === 'categorical') {
        // Pre-fill with the first available value, or empty
        initialForm[col.name] = col.distinctValues[0] || '';
      } else if (col.name.toLowerCase().includes('carga') || col.name.toLowerCase().includes('hora')) {
        // Pre-fill default average load (e.g. 40 or empty)
        initialForm[col.name] = '40';
      } else {
        initialForm[col.name] = '';
      }

      initialCustoms[col.name] = '';
      initialCustomToggles[col.name] = false;
    });

    setFormData(initialForm);
    setErrors({});
    setCustomValues(initialCustoms);
    setShowCustomInput(initialCustomToggles);
    setFormSuccess(null);
  };

  // Detect key identifier (Matrícula / Código / ID)
  const keyColumn = columns.find(col => 
    col.name.toLowerCase().includes('matríc') || 
    col.name.toLowerCase().includes('códig') || 
    col.name.toLowerCase().includes('id')
  );

  // Calculate dynamic code preview
  const getAutoGeneratedCode = () => {
    if (!keyColumn) return '';
    const isMatricula = keyColumn.name.toLowerCase().includes('matríc');
    const prefix = isMatricula ? 'PESC-2026-' : 'REG-';
    // Count rows to give sequential count
    const count = rows.length + 1;
    const numStr = isMatricula ? String(count).padStart(3, '0') : String(100 + count);
    return `${prefix}${numStr}`;
  };

  // Helper to get real field value (taking custom input if toggled)
  const getFieldValue = (colName: string) => {
    if (showCustomInput[colName]) {
      return customValues[colName] || '';
    }
    return formData[colName] || '';
  };

  const handleInputChange = (colName: string, value: string) => {
    setFormData(prev => ({ ...prev, [colName]: value }));
    if (errors[colName]) {
      setErrors(prev => ({ ...prev, [colName]: '' }));
    }
  };

  const handleCustomValueChange = (colName: string, value: string) => {
    setCustomValues(prev => ({ ...prev, [colName]: value }));
    if (errors[colName]) {
      setErrors(prev => ({ ...prev, [colName]: '' }));
    }
  };

  const toggleCustomInput = (colName: string) => {
    const isEnabled = showCustomInput[colName];
    setShowCustomInput(prev => ({ ...prev, [colName]: !isEnabled }));
    
    // If turning on, clear selection
    if (!isEnabled) {
      setFormData(prev => ({ ...prev, [colName]: '' }));
    } else {
      // If turning off, set back to default first option
      const col = columns.find(c => c.name === colName);
      if (col && col.distinctValues.length > 0) {
        setFormData(prev => ({ ...prev, [colName]: col.distinctValues[0] }));
      }
    }
  };

  const validateForm = () => {
    const newErrors: { [key: string]: string } = {};
    let isValid = true;

    columns.forEach(col => {
      // Skip validating key column if autoGenKey is checked
      if (keyColumn && col.name === keyColumn.name && autoGenKey) {
        return;
      }

      const val = getFieldValue(col.name);

      // Simple empty check
      if (!val || String(val).trim() === '') {
        newErrors[col.name] = `O campo "${col.name}" é de preenchimento obrigatório.`;
        isValid = false;
      }

      // Check numeric
      if (col.type === 'numeric' && val) {
        const num = Number(val);
        if (isNaN(num)) {
          newErrors[col.name] = `O valor do campo "${col.name}" deve ser numérico bruto.`;
          isValid = false;
        } else if (num < 0) {
          newErrors[col.name] = `O valor de "${col.name}" não pode ser negativo.`;
          isValid = false;
        }
      }
    });

    setErrors(newErrors);
    return isValid;
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (!validateForm()) {
      // Scroll to top of form or keep visible
      return;
    }

    // Compile record
    const finalRecord: DataRecord = {};

    columns.forEach(col => {
      if (keyColumn && col.name === keyColumn.name && autoGenKey) {
        finalRecord[col.name] = getAutoGeneratedCode();
      } else {
        finalRecord[col.name] = getFieldValue(col.name);
      }
    });

    // Save into Main Application State
    onAddRow(finalRecord);

    // Keep track of session additions locally so user has quick review list
    const addedAtIdx = 0; // Pre-appended at position 0
    setSessionAdditions(prev => [
      { row: finalRecord, originalIndex: addedAtIdx }, 
      ...prev
    ]);

    // Show success indicator banner
    const primaryNameVal = finalRecord['Nome Pescador'] || finalRecord['Pescador / Aluno'] || finalRecord['Cliente'] || finalRecord['Nome'] || 'Novo Registro';
    setFormSuccess(String(primaryNameVal));

    // Reset inputs but keep custom values list ready
    resetForm();
  };

  const handleRemoveSessionItem = (sessionIdx: number, originalIndex: number, label: string) => {
    if (window.confirm(`Deseja excluir "${label}" permanentemente do cache local?`)) {
      onDeleteRow(originalIndex);
      setSessionAdditions(prev => prev.filter((_, idx) => idx !== sessionIdx));
    }
  };

  // Icons mapper for spreadsheet properties to maximize visual context
  const getFieldIcon = (colName: string) => {
    const name = colName.toLowerCase();
    if (name.includes('aluno') || name.includes('pescador') || name.includes('nome') || name.includes('contat') || name.includes('client')) {
      return <User className="w-5 h-5 text-indigo-400" />;
    }
    if (name.includes('cpf') || name.includes('documento')) {
      return <AlertCircle className="w-5 h-5 text-indigo-400" />;
    }
    if (name.includes('ata')) {
      return <BookOpen className="w-5 h-5 text-indigo-400" />;
    }
    if (name.includes('nautilus') || name.includes('termo')) {
      return <CheckCircle className="w-5 h-5 text-indigo-400" />;
    }
    if (name.includes('entidade') || name.includes('colôn') || name.includes('colôn') || name.includes('comunida')) {
      return <MapPin className="w-5 h-5 text-indigo-400" />;
    }
    if (name.includes('local') || name.includes('forma') || name.includes('uf') || name.includes('cidad')) {
      return <MapPin className="w-5 h-5 text-emerald-400" />;
    }
    if (name.includes('situa') || name.includes('status') || name.includes('etapa') || name.includes('fase')) {
      return <CheckCircle className="w-5 h-5 text-indigo-400" />;
    }
    return <FileSpreadsheet className="w-5 h-5 text-indigo-400" />;
  };

  return (
    <div className="space-y-8">
      
      {/* Title Header with info context */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h3 className="text-xl font-extrabold text-white tracking-tight flex items-center gap-3">
            <span className="p-2 bg-indigo-500/15 border border-indigo-500/25 rounded-2xl text-indigo-400">
              <UserPlus className="w-6 h-6" />
            </span>
            Matrícula Dinâmica de Pescadores
          </h3>
          <p className="text-slate-400 text-xs mt-1.5 leading-relaxed">
            Este formulário se auto-adapta às colunas da aba ativa (<strong>FormacaoPescadores</strong>). Insira novos dados diretamente no cache sincronizado do aplicativo.
          </p>
        </div>
      </div>

      {formSuccess && (
        <div className="p-5 bg-emerald-500/10 border border-emerald-500/20 rounded-[2rem] flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 animate-fade-in">
          <div className="flex gap-3 items-center">
            <div className="w-10 h-10 rounded-full bg-emerald-500/20 text-emerald-400 flex items-center justify-center font-extrabold shrink-0">
              ✓
            </div>
            <div>
              <p className="text-white font-extrabold text-sm">Cadastro de Pescador Concluído!</p>
              <p className="text-emerald-400 text-xs mt-0.5">
                <strong>{formSuccess}</strong> foi registrado(a) com sucesso na planilha local.
              </p>
            </div>
          </div>
          <button 
            onClick={() => setFormSuccess(null)}
            className="text-xs font-black uppercase text-white hover:text-slate-300 bg-white/5 border border-white/10 px-4 py-2.5 rounded-xl transition-all cursor-pointer"
          >
            Fechar Aviso
          </button>
        </div>
      )}

      {/* Main Layout Divided into Form Editor & Real-Time Live Preview */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        
        {/* Dynamic Form Editor */}
        <div className="lg:col-span-7 bg-white/5 backdrop-blur-xl border border-white/10 p-6 md:p-8 rounded-[2.5rem] shadow-2xl relative">
          
          <div className="flex items-center justify-between mb-6 pb-4 border-b border-white/5">
            <h4 className="text-sm font-black text-slate-300 uppercase tracking-widest flex items-center gap-2">
              <FilePlus2 className="w-4 h-4 text-indigo-400" />
              Editor de Formulário Dinâmico
            </h4>
            <button 
              type="button"
              onClick={resetForm}
              className="text-slate-400 hover:text-white text-xs font-semibold flex items-center gap-1 bg-white/5 px-2.5 py-1.5 rounded-lg border border-white/5 hover:border-white/10 transition-all cursor-pointer"
              title="Limpar todos os campos"
            >
              <RotateCcw className="w-3 h-3" /> Reiniciar
            </button>
          </div>

          <form onSubmit={handleSubmit} className="space-y-6">
            
            {/* Render unique ID config if key exists */}
            {keyColumn && (
              <div className="p-4 bg-indigo-500/5 rounded-2xl border border-indigo-500/10 space-y-3">
                <div className="flex items-center justify-between">
                  <label className="text-xs uppercase font-extrabold tracking-wider text-slate-300 flex items-center gap-2">
                    {getFieldIcon(keyColumn.name)}
                    {keyColumn.name}
                  </label>
                  <label className="flex items-center gap-2 cursor-pointer text-xs font-bold text-slate-300">
                    <input 
                      type="checkbox" 
                      checked={autoGenKey}
                      onChange={(e) => setAutoGenKey(e.target.checked)}
                      className="rounded border-white/10 text-indigo-600 focus:ring-2 focus:ring-indigo-500 w-4 h-4 bg-indigo-950"
                    />
                    Gerar Id Sequencial
                  </label>
                </div>

                {autoGenKey ? (
                  <div className="p-3 bg-slate-950/40 rounded-xl border border-white/5 flex items-center justify-between">
                    <span className="font-mono text-xs text-indigo-300 font-extrabold">
                      {getAutoGeneratedCode()}
                    </span>
                    <span className="text-[10px] text-slate-400 uppercase font-black bg-indigo-500/10 px-2 py-0.5 rounded">
                      Automático no Envio
                    </span>
                  </div>
                ) : (
                  <div>
                    <input 
                      type="text"
                      className={`w-full bg-slate-950/40 text-white rounded-xl text-xs border p-3 focus:outline-none focus:ring-2 focus:ring-indigo-500 placeholder-slate-500 transition-colors ${
                        errors[keyColumn.name] ? 'border-rose-500/55' : 'border-white/10'
                      }`}
                      placeholder={`Digite a ${keyColumn.name} manual`}
                      value={formData[keyColumn.name] || ''}
                      onChange={(e) => handleInputChange(keyColumn.name, e.target.value)}
                    />
                    {errors[keyColumn.name] && (
                      <p className="text-rose-400 text-[11px] mt-1.5 flex items-center gap-1">
                        <AlertCircle className="w-3.5 h-3.5" />
                        {errors[keyColumn.name]}
                      </p>
                    )}
                  </div>
                )}
              </div>
            )}

            {/* Render with grid columns */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              {columns
                .filter(col => !keyColumn || col.name !== keyColumn.name)
                .map(col => {
                  const hasErr = !!errors[col.name];
                  const hasCustom = showCustomInput[col.name];

                  return (
                    <div key={col.name} className="flex flex-col space-y-1.5">
                      <div className="flex justify-between items-center">
                        <label className="text-[11px] uppercase font-bold text-slate-350 flex items-center gap-1.5">
                          {getFieldIcon(col.name)}
                          {col.name}
                        </label>

                        {/* If categorical, let them toggle a custom text input */}
                        {col.type === 'categorical' && (
                          <div className="flex items-center gap-2">
                            <button
                              type="button"
                              onClick={() => toggleCustomInput(col.name)}
                              className="text-[10px] font-black uppercase text-indigo-400 hover:text-indigo-350 transition-colors cursor-pointer"
                            >
                              {hasCustom ? 'Escolher Lista' : '+ Inserir Novo'}
                            </button>
                            
                            {(col.name === 'Entidade' || col.name === 'Local de Formação') && (
                              <>
                                <span className="text-slate-600 text-xs">|</span>
                                <button
                                  type="button"
                                  onClick={() => toggleEditOptions(col.name)}
                                  className={`text-[10px] font-black uppercase flex items-center gap-1 transition-colors cursor-pointer ${
                                    showEditOptions[col.name] ? 'text-amber-450 hover:text-amber-400' : 'text-emerald-450 hover:text-emerald-400'
                                  }`}
                                >
                                  {showEditOptions[col.name] ? 'Fechar Edição' : '✏️ Editar Opções'}
                                </button>
                              </>
                            )}
                          </div>
                        )}
                      </div>

                      {col.type === 'categorical' && !hasCustom ? (
                        <div className="space-y-1.5">
                          <select
                            required
                            value={formData[col.name] || ''}
                            onChange={(e) => handleInputChange(col.name, e.target.value)}
                            className={`w-full bg-slate-950/40 text-white rounded-2xl text-xs border p-3 focus:outline-none focus:ring-2 focus:ring-indigo-500 transition-colors cursor-pointer ${
                              hasErr ? 'border-rose-500/55' : 'border-white/10'
                            }`}
                          >
                            <option value="" className="bg-slate-900 text-slate-400">Selecione...</option>
                            {col.distinctValues.map(v => (
                              <option key={v} value={v} className="bg-slate-900 text-white">{v}</option>
                            ))}
                          </select>

                          {/* Sub-panel to edit existing options (for Entidade and Local de Formação) */}
                          {showEditOptions[col.name] && col.distinctValues.length > 0 && (
                            <div className="mt-2 p-3 bg-slate-900/80 border border-emerald-500/20 rounded-2xl space-y-2.5 animate-fade-in">
                              <p className="text-[10px] uppercase font-black text-amber-300 flex items-center gap-1">
                                <span>✏️</span> Renomear Valores da Lista:
                              </p>
                              <div className="space-y-1.5 max-h-[140px] overflow-y-auto pr-1">
                                {col.distinctValues.map((val, idx) => {
                                  const isEditing = editingOptionIndex[col.name] === idx;
                                  return (
                                    <div key={idx} className="flex items-center justify-between gap-2 p-1.5 bg-slate-950/50 rounded-xl border border-white/5">
                                      {isEditing ? (
                                        <input 
                                          type="text"
                                          className="flex-1 min-w-0 bg-slate-900 border border-emerald-500/40 text-white rounded px-2.5 py-1 text-xs focus:outline-none focus:ring-1 focus:ring-emerald-500"
                                          value={editingOptionText[col.name] || ''}
                                          onChange={(e) => setEditingOptionText(prev => ({ ...prev, [col.name]: e.target.value }))}
                                          autoFocus
                                        />
                                      ) : (
                                        <span className="text-slate-300 text-xs truncate max-w-[150px] font-medium px-2">{val}</span>
                                      )}
                                      
                                      <div className="flex gap-1.5 items-center shrink-0">
                                        {isEditing ? (
                                          <>
                                            <button
                                              type="button"
                                              onClick={() => saveEditedOption(col.name, idx, val)}
                                              className="text-[10px] font-black bg-emerald-500/20 text-emerald-300 hover:bg-emerald-500/30 border border-emerald-500/30 px-2 py-1 rounded transition-colors cursor-pointer"
                                            >
                                              Salvar
                                            </button>
                                            <button
                                              type="button"
                                              onClick={() => setEditingOptionIndex(prev => ({ ...prev, [col.name]: null }))}
                                              className="text-[10px] font-black bg-rose-500/10 text-rose-400 hover:bg-rose-500/20 border border-rose-500/10 px-2 py-1 rounded transition-colors cursor-pointer"
                                            >
                                              Volt
                                            </button>
                                          </>
                                        ) : (
                                          <button
                                            type="button"
                                            onClick={() => startEditingOption(col.name, idx, val)}
                                            className="text-[10px] font-black bg-white/5 hover:bg-white/10 text-slate-300 border border-white/5 hover:border-white/10 px-2 py-0.5 rounded transition-all cursor-pointer"
                                          >
                                            Editar
                                          </button>
                                        )}
                                      </div>
                                    </div>
                                  );
                                })}
                              </div>
                              <p className="text-[9px] text-slate-400 italic mt-1 leading-normal">
                                * Salvar mudará esse valor em todos os alunos já cadastrados.
                              </p>
                            </div>
                          )}
                        </div>
                      ) : col.type === 'categorical' && hasCustom ? (
                        <div className="relative">
                          <input 
                            type="text"
                            required
                            placeholder={`Escreva novo(a) ${col.name}`}
                            value={customValues[col.name] || ''}
                            onChange={(e) => handleCustomValueChange(col.name, e.target.value)}
                            className={`w-full bg-indigo-500/5 text-white rounded-2xl text-xs border p-3 focus:outline-none focus:ring-2 focus:ring-indigo-500 placeholder-slate-500 transition-colors pr-10 ${
                              hasErr ? 'border-rose-500/55 border-dashed font-bold' : 'border-indigo-500/30 font-bold'
                            }`}
                          />
                          <span className="absolute right-3 top-1/2 -translate-y-1/2 text-[9px] uppercase font-black text-indigo-400 bg-indigo-500/20 px-1.5 py-0.5 rounded">
                            Novo
                          </span>
                        </div>
                      ) : col.type === 'date' ? (
                        <input 
                          type="date"
                          required
                          value={formData[col.name] || ''}
                          onChange={(e) => handleInputChange(col.name, e.target.value)}
                          className={`w-full bg-slate-950/40 text-white rounded-2xl text-xs border p-3 focus:outline-none focus:ring-2 focus:ring-indigo-500 transition-colors ${
                            hasErr ? 'border-rose-500/55' : 'border-white/10'
                          }`}
                        />
                      ) : col.type === 'numeric' ? (
                        <div className="relative">
                          <input 
                            type="number"
                            required
                            pattern="[0-9]*"
                            placeholder="0"
                            value={formData[col.name] || ''}
                            onChange={(e) => handleInputChange(col.name, e.target.value)}
                            className={`w-full bg-slate-950/40 text-white rounded-2xl text-xs border p-3 focus:outline-none focus:ring-2 focus:ring-indigo-500 transition-colors pr-12 ${
                              hasErr ? 'border-rose-500/55' : 'border-white/10'
                            }`}
                          />
                          {col.name.toLowerCase().includes('carga') && (
                            <span className="absolute right-3.5 top-1/2 -translate-y-1/2 font-mono text-[10px] text-slate-400">
                              horas
                            </span>
                          )}
                        </div>
                      ) : (
                        <input 
                          type="text"
                          required
                          placeholder={`Escrever ${col.name.toLowerCase()}`}
                          value={formData[col.name] || ''}
                          onChange={(e) => handleInputChange(col.name, e.target.value)}
                          className={`w-full bg-slate-950/40 text-white rounded-2xl text-xs border p-3 focus:outline-none focus:ring-2 focus:ring-indigo-500 placeholder-slate-500 transition-colors ${
                            hasErr ? 'border-rose-500/55' : 'border-white/10'
                          }`}
                        />
                      )}

                      {hasErr && (
                        <p className="text-rose-400 text-[10px] flex items-center gap-1.5 leading-tight">
                          <AlertCircle className="w-3 h-3 shrink-0" />
                          {errors[col.name]}
                        </p>
                      )}
                    </div>
                  );
                })}
            </div>

            {/* Dynamic visual tips to guide fishermen coordinator */}
            <div className="p-4 bg-slate-950/40 rounded-2xl border border-white/5 text-[11px] text-slate-400 leading-relaxed flex items-start gap-2.5">
              <span className="w-5 h-5 rounded-lg bg-indigo-500/10 text-indigo-400 shrink-0 font-extrabold flex items-center justify-center">💡</span>
              <p>
                <strong>Incrementos em Cascata:</strong> O sistema atualiza os filtros de pesquisa instantaneamente em todo o painel e insere as restrições nas visualizações Kanban assim que você clicar no botão abaixo.
              </p>
            </div>

            <button
              type="submit"
              className="w-full bg-indigo-600 hover:bg-indigo-500 active:bg-indigo-700 text-white font-extrabold text-sm py-4 rounded-2xl transition-all shadow-xl hover:shadow-indigo-600/20 cursor-pointer min-h-[52px] uppercase tracking-wider flex items-center justify-center gap-2"
            >
              <UserPlus className="w-5 h-5" /> Confirmar e Cadastrar Aluno
            </button>

          </form>
        </div>

        {/* Real-time Dynamic Student Card Preview Panel */}
        <div className="lg:col-span-4 space-y-6">
          
          {/* Card Preview Container */}
          <div className="bg-gradient-to-br from-indigo-950/80 to-slate-900/90 border border-white/10 p-6 rounded-[2.5rem] shadow-xl relative overflow-hidden backdrop-blur-xl">
            <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-500/10 rounded-full blur-2xl pointer-events-none" />
            
            <span className="text-[10px] uppercase font-black text-indigo-300 bg-indigo-500/20 px-3 py-1 rounded-full border border-indigo-500/10 inline-block mb-4">
              📝 CRachá do Pescador (Ficha)
            </span>
 
            {/* The Visual Card */}
            <div className="bg-slate-950/60 p-5 rounded-[2rem] border border-white/5 space-y-5 shadow-lg">
              
              {/* Card top banner */}
              <div className="flex justify-between items-start">
                <div className="space-y-1">
                  <p className="text-[10px] uppercase text-slate-400 font-extrabold tracking-widest font-mono">
                    {keyColumn?.name || 'Matrícula'}
                  </p>
                  <p className="text-sm font-mono font-black text-indigo-300">
                    {autoGenKey ? getAutoGeneratedCode() : (formData[keyColumn?.name || ''] || 'AUTO-GERADO')}
                  </p>
                </div>
                
                {/* Dynamically Styled Seal of Status */}
                {(() => {
                  const sVal = String(getFieldValue('Situação') || getFieldValue('Status') || 'Pendente').toLowerCase();
                  const isConcl = sVal.includes('concl') || sVal.includes('aprov');
                  
                  return (
                    <span className={`inline-flex items-center px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-wider border ${
                      isConcl ? 'bg-emerald-500/10 text-emerald-300 border-emerald-500/20' :
                      'bg-amber-500/10 text-amber-300 border-amber-500/20'
                    }`}>
                      {getFieldValue('Situação') || 'Pendente'}
                    </span>
                  );
                })()}
              </div>
 
              {/* Student Name */}
              <div className="space-y-0.5">
                <p className="text-[9px] uppercase font-bold text-slate-400 tracking-wider">Nome Pescador</p>
                <h5 className="font-black text-white text-lg tracking-tight leading-snug truncate">
                  {getFieldValue('Nome Pescador') || getFieldValue('Pescador / Aluno') || getFieldValue('Nome') || (
                    <span className="text-slate-600 italic font-medium text-sm">Preencha o nome...</span>
                  )}
                </h5>
              </div>

              {/* CPF */}
              <div className="space-y-0.5">
                <p className="text-[9px] uppercase font-bold text-slate-400 tracking-wider">CPF</p>
                <p className="font-mono text-sm font-bold text-indigo-200">
                  {getFieldValue('CPF') || '---.---.------'}
                </p>
              </div>
 
              {/* Entidade & Local de Formação */}
              <div className="grid grid-cols-2 gap-4 pt-1.5 border-t border-white/5 text-xs">
                <div>
                  <p className="text-[9px] uppercase font-bold text-slate-400 tracking-wider">Entidade</p>
                  <p className="font-semibold text-slate-200 truncate mt-0.5">
                    {getFieldValue('Entidade') || 'Não Selecionada'}
                  </p>
                </div>
                <div>
                  <p className="text-[9px] uppercase font-bold text-slate-400 tracking-wider">Local de Formação</p>
                  <p className="font-semibold text-slate-200 truncate mt-0.5">
                    {getFieldValue('Local de Formação') || 'Não Selecionado'}
                  </p>
                </div>
              </div>
 
              {/* Presence ATA 1 & ATA 2 status */}
              <div className="grid grid-cols-2 gap-4 pt-3 border-t border-white/5 text-xs">
                <div>
                  <p className="text-[9px] uppercase font-bold text-slate-400 tracking-wider">ATA 1</p>
                  <span className={`inline-block text-[10px] font-bold px-2 py-0.5 rounded-md mt-1 border ${
                    getFieldValue('ATA1') === 'Presente' 
                      ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/15' 
                      : 'bg-rose-500/10 text-rose-400 border-rose-500/15'
                  }`}>
                    {getFieldValue('ATA1') || 'Ausente'}
                  </span>
                </div>
                <div>
                  <p className="text-[9px] uppercase font-bold text-slate-400 tracking-wider">ATA 2</p>
                  <span className={`inline-block text-[10px] font-bold px-2 py-0.5 rounded-md mt-1 border ${
                    getFieldValue('ATA2') === 'Presente' 
                      ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/15' 
                      : 'bg-rose-500/10 text-rose-400 border-rose-500/15'
                  }`}>
                    {getFieldValue('ATA2') || 'Ausente'}
                  </span>
                </div>
              </div>

              {/* Nautilus and Termo */}
              <div className="grid grid-cols-2 gap-4 pt-3 border-t border-white/5 text-xs">
                <div>
                  <p className="text-[9px] uppercase font-bold text-slate-400 tracking-wider">Nautilus</p>
                  <span className={`inline-block text-[10px] font-bold px-2 py-0.5 rounded-md mt-1 border ${
                    getFieldValue('Nautilus') === 'Cadastrado' 
                      ? 'bg-indigo-500/20 text-indigo-300 border-indigo-500/30' 
                      : 'bg-slate-800 text-slate-400 border-white/5'
                  }`}>
                    {getFieldValue('Nautilus') || 'Não Cadastrado'}
                  </span>
                </div>
                <div>
                  <p className="text-[9px] uppercase font-bold text-slate-400 tracking-wider">Termo</p>
                  <span className={`inline-block text-[10px] font-bold px-2 py-0.5 rounded-md mt-1 border ${
                    getFieldValue('Termo') === 'Assinou' 
                      ? 'bg-emerald-500/10 text-emerald-300 border-emerald-500/15' 
                      : 'bg-slate-800 text-slate-400 border-white/5'
                  }`}>
                    {getFieldValue('Termo') || 'Não Assinou'}
                  </span>
                </div>
              </div>
 
            </div>
          </div>
 
          {/* Session additions list tracker to undo/manage newly enrolled items */}
          <div className="bg-white/5 backdrop-blur-md border border-white/10 p-5 rounded-[2rem] space-y-4">
            <h5 className="font-bold text-white text-xs uppercase tracking-wider flex items-center gap-2">
              <span className="p-1 rounded bg-indigo-500/10 text-indigo-400">⚡</span>
              Cadastros Nesta Sessão ({sessionAdditions.length})
            </h5>

            {sessionAdditions.length > 0 ? (
              <div className="space-y-3 max-h-[220px] overflow-y-auto pr-1">
                {sessionAdditions.map((item, idx) => {
                  const code = String(item.row[keyColumn?.name || 'Matrícula'] || '');
                  const nameStr = String(item.row['Pescador / Aluno'] || item.row['Cliente'] || item.row['Nome'] || 'Sem Nome');
                  const targetLabel = `${code} ${nameStr}`;

                  return (
                    <div 
                      key={idx} 
                      className="bg-slate-950/40 p-3 rounded-xl border border-white/5 flex items-center justify-between gap-3 text-xs"
                    >
                      <div className="min-w-0 flex-1">
                        <div className="flex items-center gap-2">
                          <span className="font-mono text-[10px] font-black text-indigo-300">
                            {code}
                          </span>
                          <span className="text-slate-400 text-[10px] font-medium">
                            {String(item.row['Curso'] || '').slice(0, 20)}...
                          </span>
                        </div>
                        <p className="font-bold text-white truncate mt-0.5">
                          {nameStr}
                        </p>
                      </div>

                      <button
                        onClick={() => handleRemoveSessionItem(idx, item.originalIndex, nameStr)}
                        className="text-rose-400 hover:text-rose-350 p-2 hover:bg-rose-500/10 rounded-lg transition-colors cursor-pointer"
                        title="Remover Registro"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  );
                })}
              </div>
            ) : (
              <p className="text-slate-400 text-[11px] py-4 text-center italic border border-dashed border-white/5 rounded-2xl">
                Nenhum cadastro feito no cache local nesta sessão ainda.
              </p>
            )}
          </div>

        </div>

      </div>

    </div>
  );
}
